name: gallery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.3
  equatable: ^2.0.5
  http: ^1.2.0
  stream_transform: ^2.1.0
  go_router: ^13.0.1
  flutter_dotenv: ^5.1.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
